---
program: wandb-agent.py
project: vcmi
# method: grid
method: random
name: PPO-3
metric:
  name: rollout/ep_rew_mean
  goal: maximize
parameters:
  action: { value: train_ppo }
  c:
    parameters:
      model_load_file: { value: ~ }
      out_dir_template: { value: "data/PPO-{run_id}" }
      log_tensorboard: { value: true }
      total_timesteps: { value: !!float 10e3 }
      n_checkpoints: { value: 5 }
      learner_kwargs:
        parameters:
          policy: { value: "MlpPolicy" }
          use_sde: { value: false }
          sde_sample_freq: { value: -1 }
          n_steps: { value: 512 }
          batch_size: { value: 64 }
          n_epochs: { value: 10 }
          gamma: { value: 0.999 }
          gae_lambda: { value: 0.98 }
          clip_range: { value: 0.4 }
          normalize_advantage: { value: true }
          ent_coef: { value: 0.0001 }
          vf_coef: { value: 0.5 }
          max_grad_norm: { value: 0.5 }
      learner_lr_schedule:
        values:
          - "const_0.0001"
      env_kwargs:
        parameters:
          mapname: { value: "AI-1.vmap" }
          max_steps: { value: 500 }
          consecutive_error_reward_factor: { values: [-2] }
          sparse_info: { value: true }
