---
program: wandb-agent.py
project: vcmi
method: grid
metric:
  name: rollout/ep_rew_mean
  goal: maximize
parameters:
  action: { value: train_ppo }
  c:
    parameters:
      model_load_file: { value: ~ }
      out_dir_template: { value: "data/PPO-{run_id}" }
      log_tensorboard: { value: true }
      total_timesteps: { value: !!float 3e6 }
      max_episode_steps: { value: 5000 }
      n_checkpoints: { value: 5 }
      learner_kwargs:
        parameters:
          policy: { value: "MlpPolicy" }
          use_sde: { value: false }
          sde_sample_freq: { value: -1 }
          n_steps: { value: 2048 }
          batch_size: { value: 64 }
          n_epochs: { value: 10 }
          gamma: { value: 0.99 }
          gae_lambda: { value: 0.98 }
          clip_range: { value: 0.4 }
          normalize_advantage: { value: true }
          ent_coef: { value: 0.0001 }
          vf_coef: { value: 0.5 }
          max_grad_norm: { value: 0.5 }
      learner_lr_schedule:
        values:
          - "exp_decay_0.03_0.0001_0.5_10"
          - "const_0.0003"
      env_kwargs:
        parameters:
          mapname: { value: "AI-1.vmap" }
          consecutive_error_reward_factor: { values: [-1, -2] }
