---
program: wandb-agent.py
project: vcmi
method: grid
metric:
  name: rollout/ep_rew_mean
  goal: maximize
parameters:
  action: { value: train_qrdqn }
  c:
    parameters:
      model_load_file: { value: ~ }
      out_dir_template: { value: "data/QRDQN-{run_id}" }
      log_tensorboard: { value: true }
      total_timesteps: { value: 2e6 }
      max_episode_steps: { value: 5000 }
      n_checkpoints: { value: 10 }
      learner_kwargs:
        parameters:
          policy: { value: "MlpPolicy" }
          buffer_size: { value: 100000 }
          learning_starts: { value: 100000 }
          batch_size: { value: 64 }
          tau: { value: 1.0 }
          gamma: { value: 0.99 }
          train_freq: { value: 4 }
          gradient_steps: { value: 1 }
          target_update_interval: { value: 512 }
          exploration_fraction: { value: 0.3 }
          exploration_initial_eps: { value: 0.2 }
          exploration_final_eps: { value: 0 }
      learner_lr_schedule: { values: ["const_0.001", "const_0.0001"] }
      env_kwargs:
        parameters:
          mapname: { value: "AI-1.vmap" }
          consecutive_error_reward_factor: { value: -2 }
