---
wandb_project: vcmi-gym
group_id: hybrids
run_id: 5x7v4e1n
resume: True
overwrite: ["lr_schedule.start"]
# overwrite: ["learning_rate", "env.term_reward_mult"]
out_dir_template: "data/{group_id}/{run_id}"

lr_schedule: { start: 1.0e-6 }
