---
group_id: crl
run_id: fc1024-gd0.99
resume: True
overwrite: ["mapmask"]
# overwrite: ["learning_rate", "env.term_reward_mult"]
out_dir_template: "data/{group_id}/{run_id}"
mapmask: "gym/generated/B*.vmap"
