---
wandb_project: vcmi-gym
group_id: hybrids
run_id: d8bxeoi8
resume: True
overwrite: ["save_every"]
# overwrite: ["learning_rate", "env.term_reward_mult"]
out_dir_template: "data/{group_id}/{run_id}"

save_every: 1200
