---
group_id: crl
run_id: clone-BattleAI
resume: True
overwrite: ["learning_rate"]
# overwrite: ["learning_rate", "env.term_reward_mult"]
out_dir_template: "data/{group_id}/{run_id}"
learning_rate: 0.00001
