from vcmi_gym.envs.v12.pyconnector import (
    N_ACTIONS,
    STATE_SIZE_GLOBAL,
    STATE_SIZE_ONE_PLAYER,
    STATE_SIZE_ONE_HEX,
    GLOBAL_ATTR_MAP,
    PLAYER_ATTR_MAP,
    HEX_ATTR_MAP,
    HEX_ACT_MAP,
)

# Helper constants for reconstructing obs/mask
STATE_HEXES_INDEX_START = STATE_SIZE_GLOBAL + 2*STATE_SIZE_ONE_PLAYER
HEX_MASK_INDEX_START = HEX_ATTR_MAP["ACTION_MASK"][1]
HEX_MASK_INDEX_END = HEX_MASK_INDEX_START + HEX_ATTR_MAP["ACTION_MASK"][2]
