---
fps: -1
reset_delay: 0
# model_file: "data/M2-PPO-20231123_184314/66b67_00001_1_ent_coef=0.0025,gamma=0.9120,learning_rate=0.0007_2023-11-23_18-43-16/checkpoint_000047/model.zip"
model_mod: "sb3_contrib"
model_cls: "MaskablePPO"

# model_file: "data/QRDQN-qfo6cz71/model_2000000_steps.zip"
# model_mod: "sb3_contrib"
# model_cls: "QRDQN"

env_kwargs:
  max_steps: 500
  reward_clip_mod: ~
  reward_dmg_factor: 5
  vcmi_loglevel_global: "error"
  vcmi_loglevel_ai: "error"
  vcmienv_loglevel: "WARN"
  consecutive_error_reward_factor: -1
  sparse_info: true
  step_reward_mult: 0.01
  term_reward_mult: 1

  attacker: "MMAI_USER"  # MMAI_USER / MMAI_MODEL / StupidAI / BattleAI
  defender: "StupidAI"   # MMAI_USER / MMAI_MODEL / StupidAI / BattleAI

env_wrappers: []
