---
fps: -1
reset_delay: 5
model_file: "data/PPO-PB2-2023-11-23_04:45:05/5024c_00002_2_ent_coef=0.0029,gamma=0.9500,learning_rate=0.0005_2023-11-23_04-45-07/checkpoint_000003/model.zip"
model_mod: "stable_baselines3"
model_cls: "PPO"

# model_file: "data/QRDQN-qfo6cz71/model_2000000_steps.zip"
# model_mod: "sb3_contrib"
# model_cls: "QRDQN"

env_kwargs:
  __include__: "config/env.yml"
  render_each_step: true
  consecutive_error_reward_factor: -1
  sparse_info: false

env_wrappers: []
