---
fps: 10
reset_delay: 5
model_file: "/Users/simo/Projects/vcmi-gym/data/PPO-PB2-2023-11-21_05:46:25/train_function_8cd85_00004_4_2023-11-21_05-46-27/checkpoint_000022/model.zip"
model_mod: "stable_baselines3"
model_cls: "PPO"

# model_file: "data/QRDQN-qfo6cz71/model_2000000_steps.zip"
# model_mod: "sb3_contrib"
# model_cls: "QRDQN"

env_kwargs:
  __include__: "config/env.yml"
  render_each_step: true
  consecutive_error_reward_factor: -5

env_wrappers: []
