---
fps: -1
reset_delay: 5
model_file: "data/M2-PPO-20231123_123144/80b61_00000_0_ent_coef=0.0011,gamma=0.9953,learning_rate=0.0009_2023-11-23_12-31-46/checkpoint_000004/model.zip"
model_mod: "stable_baselines3"
model_cls: "PPO"

# model_file: "data/QRDQN-qfo6cz71/model_2000000_steps.zip"
# model_mod: "sb3_contrib"
# model_cls: "QRDQN"

env_kwargs:
  __include__: "config/env.yml"
  render_each_step: true
  consecutive_error_reward_factor: -1
  sparse_info: false

env_wrappers: []
