---
seed: ~
run_id: ~
model_load_file: "data/M8-PBT-MPPO-20231204_191243/576e9_00000/checkpoint_000139/model.zip"
out_dir_template: "data/MPPO-{run_id}"
log_tensorboard: true
progress_bar: true
total_timesteps: !!float 1e6
n_checkpoints: 5
n_envs: 1

# vcmi_cnn_kwargs: ~  # use "~" for generic MlpPolicy
vcmi_cnn_kwargs:
  features_dim: 128  # TODO: experiment with 16, 512, etc.

learner_kwargs:
  policy: "MlpPolicy"

  n_steps: 512
  batch_size: 64
  n_epochs: 10

  gamma: 0.95
  gae_lambda: 0.98
  clip_range: 0.2
  normalize_advantage: true
  ent_coef: 0.002474
  vf_coef: 0.5
  max_grad_norm: 0.5

# Examples:
#   * "const_0.001"
#   * "lin_decay_0.03_0.0001_0.75"
#   * "exp_decay_0.03_0.0001_0.5_5"
learner_lr_schedule: "const_0.000515"

env_kwargs:
  __include__: "config/env.yml"
  mapname: "ai/M8.vmap"
  consecutive_error_reward_factor: -1
env_wrappers: []
