---
seed: ~
run_id: ~
model_load_file: ~
out_dir_template: "data/MPPO-{run_id}"
log_tensorboard: true
progress_bar: true
total_timesteps: !!float 100000
n_checkpoints: 1
n_envs: 1

# vcmi_cnn_kwargs: ~  # use "~" for generic MlpPolicy
vcmi_cnn_kwargs:
  features_dim: 512  # TODO: experiment a lot with those. Try 16, 512, etc.

learner_kwargs:
  # XXX: replaced by CnnPolicy if vcmi_cnn_kwargs is present
  policy: "MlpPolicy"

  n_steps: 2048
  batch_size: 64
  n_epochs: 10


  gamma: 0.9796
  gae_lambda: 0.8
  clip_range: 0.4
  normalize_advantage: true
  ent_coef: 0.002474
  vf_coef: 0.1
  max_grad_norm: 4.545

# Examples:
#   * "const_0.001"
#   * "lin_decay_0.03_0.0001_0.75"
#   * "exp_decay_0.03_0.0001_0.5_5"
learner_lr_schedule: "const_0.0005169"

env_kwargs:
  __include__: "config/env.yml"
  mapname: "ai/generated/A01.vmap"
  consecutive_error_reward_factor: -1
env_wrappers: []

