from collections import OrderedDict

N_ACTIONS = 1322
STATE_SIZE_GLOBAL = 6
STATE_SIZE_ONE_PLAYER = 10
STATE_SIZE_ONE_HEX = 101

GLOBAL_ATTR_MAP = OrderedDict([
    ('BATTLE_SIDE', ('CATEGORICAL_STRICT_NULL', 0, 2, 1)),
    ('BATTLE_WINNER', ('CATEGORICAL_EXPLICIT_NULL', 2, 3, 1)),
    ('BFIELD_VALUE_NOW_REL0', ('LINNORM_STRICT_NULL', 5, 1, 100))
])

PLAYER_ATTR_MAP = OrderedDict([
    ('ARMY_VALUE_NOW_REL', ('LINNORM_STRICT_NULL', 0, 1, 100)),
    ('ARMY_VALUE_NOW_REL0', ('LINNORM_STRICT_NULL', 1, 1, 100)),
    ('VALUE_KILLED_REL', ('LINNORM_STRICT_NULL', 2, 1, 100)),
    ('VALUE_KILLED_ACC_REL0', ('LINNORM_STRICT_NULL', 3, 1, 100)),
    ('VALUE_LOST_REL', ('LINNORM_STRICT_NULL', 4, 1, 100)),
    ('VALUE_LOST_ACC_REL0', ('LINNORM_STRICT_NULL', 5, 1, 100)),
    ('DMG_DEALT_REL', ('LINNORM_STRICT_NULL', 6, 1, 100)),
    ('DMG_DEALT_ACC_REL0', ('LINNORM_STRICT_NULL', 7, 1, 100)),
    ('DMG_RECEIVED_REL', ('LINNORM_STRICT_NULL', 8, 1, 100)),
    ('DMG_RECEIVED_ACC_REL0', ('LINNORM_STRICT_NULL', 9, 1, 100))
])

HEX_ATTR_MAP = OrderedDict([
    ('Y_COORD', ('CATEGORICAL_STRICT_NULL', 0, 11, 10)),
    ('X_COORD', ('CATEGORICAL_STRICT_NULL', 11, 15, 14)),
    ('STATE_MASK', ('BINARY_STRICT_NULL', 26, 4, 15)),
    ('ACTION_MASK', ('BINARY_ZERO_NULL', 30, 8, 255)),
    ('IS_REAR', ('CATEGORICAL_EXPLICIT_NULL', 38, 3, 1)),
    ('STACK_SIDE', ('CATEGORICAL_EXPLICIT_NULL', 41, 3, 1)),
    ('STACK_QUANTITY', ('EXPNORM_EXPLICIT_NULL', 44, 2, 1500)),
    ('STACK_ATTACK', ('EXPNORM_EXPLICIT_NULL', 46, 2, 80)),
    ('STACK_DEFENSE', ('EXPNORM_EXPLICIT_NULL', 48, 2, 80)),
    ('STACK_SHOTS', ('EXPNORM_EXPLICIT_NULL', 50, 2, 32)),
    ('STACK_DMG_MIN', ('EXPNORM_EXPLICIT_NULL', 52, 2, 100)),
    ('STACK_DMG_MAX', ('EXPNORM_EXPLICIT_NULL', 54, 2, 100)),
    ('STACK_HP', ('EXPNORM_EXPLICIT_NULL', 56, 2, 1300)),
    ('STACK_HP_LEFT', ('EXPNORM_EXPLICIT_NULL', 58, 2, 1300)),
    ('STACK_SPEED', ('EXPNORM_EXPLICIT_NULL', 60, 2, 30)),
    ('STACK_QUEUE_POS', ('EXPNORM_EXPLICIT_NULL', 62, 2, 15)),
    ('STACK_VALUE_ONE', ('EXPNORM_EXPLICIT_NULL', 64, 2, 180000)),
    ('STACK_FLAGS', ('BINARY_EXPLICIT_NULL', 66, 15, 16383)),
    ('STACK_VALUE_REL', ('LINNORM_EXPLICIT_NULL', 81, 2, 100)),
    ('STACK_VALUE_REL0', ('LINNORM_EXPLICIT_NULL', 83, 2, 100)),
    ('STACK_VALUE_KILLED_REL', ('LINNORM_EXPLICIT_NULL', 85, 2, 100)),
    ('STACK_VALUE_KILLED_ACC_REL0', ('LINNORM_EXPLICIT_NULL', 87, 2, 100)),
    ('STACK_VALUE_LOST_REL', ('LINNORM_EXPLICIT_NULL', 89, 2, 100)),
    ('STACK_VALUE_LOST_ACC_REL0', ('LINNORM_EXPLICIT_NULL', 91, 2, 100)),
    ('STACK_DMG_DEALT_REL', ('LINNORM_EXPLICIT_NULL', 93, 2, 100)),
    ('STACK_DMG_DEALT_ACC_REL0', ('LINNORM_EXPLICIT_NULL', 95, 2, 100)),
    ('STACK_DMG_RECEIVED_REL', ('LINNORM_EXPLICIT_NULL', 97, 2, 100)),
    ('STACK_DMG_RECEIVED_ACC_REL0', ('LINNORM_EXPLICIT_NULL', 99, 2, 100))
])
