---
group_id: test
run_name: "mppo sideswap test"
tags: ["Map-4096-mixstack", "StupidAI"]

wandb_project: vcmi-gym
run_id: ~
resume: False
overwrite: ["lr_schedule.start", "gamma"]
# overwrite: ["learning_rate", "weight_decay"]

notes: ""

# agent_load_file: ~
agent_load_file: "data/PBT-mppo-float-obstacle+sideswap-20240515_184107/8d231_00003/checkpoint_000040/agent.pt"
vsteps_total: 0  # exp_decay requires vsteps_total or seconds_total
seconds_total: 0  # mutually-exclusive with vsteps_total
rollouts_per_mapchange: 0
rollouts_per_log: 1
rollouts_per_table_log: 0
opponent_load_file: ~
success_rate_target: ~
ep_rew_mean_target: ~
quit_on_target: false
mapside: "attacker"  # attacker/defender; irrelevant if env.swap_sides > 0
mapmask: "gym/generated/4096/4096-mixstack-300K-01.vmap"
randomize_maps: false
save_every: 3600  # seconds
permasave_every: 10800  # seconds
max_saves: 3
out_dir_template: "data/{group_id}/{run_id}"  # XXX: relative to cwd()

# SBM = StupidAI, BattleAI, MMAI_MODEL
opponent_sbm_probs: [1, 0, 0]
opponent_load_file: ~

num_envs: 1

network:
  features_extractor:
    - {t: "Flatten"}
    # => (B, 90255)  # 165*547
    - {t: "Unflatten", dim: 1, unflattened_size: [1, 14190]}
    # => (B, 1, 90255)
    - {t: "Conv1d", in_channels: 1, out_channels: 32, kernel_size: 86, stride: 86, padding: 0}
    - {t: "Flatten"}
    # => (B, 5280)
    - {t: "Linear", in_features: 5280, out_features: 1024}
    - {t: "Tanh"}
    # => (B, 1024)

  actor: {t: "Linear", in_features: 1024, out_features: 2311}
  critic: {t: "Linear", in_features: 1024, out_features: 1}

#
# PPO Hyperparams
#

clip_coef: 0.4
clip_vloss: false
ent_coef: 0
gae_lambda: 0.94
gamma: 0.85
lr_schedule: { mode: const, start: 5.0e-7, end: 1.0e-6, rate: 10 }
max_grad_norm: 5
norm_adv: true
num_minibatches: 4   # minibatch_size = rollout_buffer/num_minibatches
num_steps: 512       # rollout_buffer = num_steps*num_envs
update_epochs: 2    # full passes of rollout_buffer
vf_coef: 0.575
weight_decay: 0

env:
  encoding_type: "float"
  reward_dmg_factor: 5
  step_reward_fixed: -100
  step_reward_mult: 1
  term_reward_mult: 0
  reward_clip_tanh_army_frac: 1
  reward_army_value_ref: 500
  random_heroes: 1
  random_obstacles: 1
  swap_sides: 0

env_wrappers: []
logparams: {}
