@startuml "arch-vcmi-fullyconv"
' left to right direction

skinparam defaultTextAlignment center
skinparam NoteTextAlignment left

<style>
Usecase {
  BackGroundColor #efe
}


</style>

'''
''' Utility functions
'''

!function $replace($txt, $search, $repl)
  !$replaced = ""
  !while %strpos($txt, $search) >= 0
    !$position = %strpos($txt, $search)
    !$replaced = $replaced + %substr($txt, 0, $position) + $repl
    !$txt = %substr($txt, $position + %strlen($search))
  !endwhile
  !return $replaced + $txt
!endfunction

' Wraps each line of $txt within $open and $close
' Example:
'   $tagged_text("<color:red>", "two\nlines", "</color>")
'   => "<color:red>two</color>\n<color:red>lines</color>")"
!function $tagged_text($open, $txt, $close) return $open + $replace($txt, "\n", $close+"\n"+$open) + $close

!function $node_text($name) return $tagged_text("<b>", $name, "</b>")
!function $node_text($name, $desc) return $node_text($name)+"\n"+$tagged_text("<font:monospaced><size:10>", $desc, "</size></font>")
!function $node_text($name, $desc, $txt) return $node_text($name, $desc)+"\n\n"+$tagged_text("<color:888><size:10>", $txt, "</size></color>")

'''
''' Node types
'''

' Data
!procedure $Data($id, $name)
  Usecase $id as "$node_text($name)"
!endprocedure

!procedure $Data($id, $name, $desc)
  Usecase $id as "$node_text($name, $desc)"
!endprocedure

!procedure $Data($id, $name, $desc, $txt)
  Usecase $id as "$node_text($name, $desc, $txt)"
!endprocedure

' FC (FC)
!procedure $FC($id, $name, $desc)
  Hexagon $id as "$node_text($name, $desc)"
!endprocedure
!procedure $FC($id, $name, $desc, $txt)
  Hexagon $id as "$node_text($name, $desc, $txt)"
!endprocedure

' Transformer
!procedure $Transformer($id, $name, $desc)
  Queue $id as "$node_text($name, $desc)"
!endprocedure
!procedure $Transformer($id, $name, $desc, $txt)
  Queue $id as "$node_text($name, $desc, $txt)"
!endprocedure

' Convolution
!procedure $Convolution($id, $name, $desc)
  Node $id as "$node_text($name, $desc)"
!endprocedure
!procedure $Convolution($id, $name, $desc, $txt)
  Node $id as "$node_text($name, $desc, $txt)"
!endprocedure

' Output
!procedure $Output($id, $name)
  Component $id as "$node_text($name)" #orange
!endprocedure

!procedure $Output($id, $name, $desc)
  Component $id as "$node_text($name, $desc)" #orange
!endprocedure

' Condition
!procedure $Condition($id, $name)
  Boundary $id as "$node_text($name)"
!endprocedure

!procedure $Condition($id, $name, $desc)
  Boundary $id as "$node_text($name, $desc)"
!endprocedure

' LSTM
!procedure $LSTM($id, $name)
  Collections $id as "$node_text($name)"
!endprocedure

!procedure $LSTM($id, $name, $desc)
  Collections $id as "$node_text($name, $desc)"
!endprocedure

' Reshape
!procedure $Reshape($id)
  Control $id as " "
!endprocedure

' Activation
!procedure $Activation($id, $name)
  Action $id as "$name"
!endprocedure

' Sum / Mean / etc.
!procedure $Op($id, $name)
  Agent $id as "$name"
!endprocedure
!procedure $Op($id, $name, $txt)
  ' Agent $id as "$node_text($name, "", $txt)"
  Agent $id as "$name\n$tagged_text("<color:888><size:10>", $txt, "</size></color>")"
!endprocedure

' Link
!procedure $Link($a, $b, $dim)
  $a --> $b : " $dim "
!endprocedure
!procedure $Link($a, $b, $dim, $txt)
  ' The newline causes a bug where the 1st line appears
  ' on the top-left side
  ' ...but it looks better that way
  $a --> $b : " $dim "\n$txt
!endprocedure

' Link
!procedure $LinkAct($a, $b, $dim)
  $a -0-> $b : " $dim "
!endprocedure
!procedure $LinkAct($a, $b, $dim, $txt)
  ' The newline causes a bug where the 1st line appears
  ' on the top-left side
  ' ...but it looks better that way
  $a -0-> $b : " $dim "\n$txt
!endprocedure

' title "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"
' left to right direction

$Data(state, "State", "", "<<H3 screenshot here>>")
$Data(obs_stacks, "Stack data", "20 stacks\n**<<S>>** attributes each", "S=102")
$Data(obs_hexes, "Hex data", "165 hexes\n**<<H>>** attributes each", "H=65")
$Data(obs_misc, "Misc. data", "**<<M>>** attributes", "M=4")
$Link(state, obs_stacks, "")
$Link(state, obs_hexes, "")
$Link(state, obs_misc, "")

$FC(fc_stacks, "FC", "S → 256 → 32", "20 channels")
$FC(fc_hexes, "FC", "S → 256 → 16", "165 channels")
$FC(fc_misc, "FC", "M → 16 → 4")
$Link(obs_misc, fc_misc, "(M,)")
$Link(obs_hexes, fc_hexes, "(165, H)")
$Link(obs_stacks, fc_stacks, "(20, S)")

$Op(flatten_hexes, "Flatten")
$Op(flatten_stacks, "Flatten")
$Link(fc_hexes, flatten_hexes, "(165, 16)")
$Link(fc_stacks, flatten_stacks, "(20, 32)")

$FC(fc2_stacks, "FC", "2640 → 256")
$FC(fc2_hexes, "FC", "640 → 256")
$Link(flatten_hexes, fc2_hexes, "(256,)")
$Link(flatten_stacks, fc2_stacks, "(256,)")

$Op(concat, "Concat")

$Link(fc_misc, concat, "(4,)")
fc2_stacks -> concat : (256,)
concat <- fc2_hexes : (256,)

$LSTM(lstm, "LSTM", "hidden_size=256\nlayers=3\nseq_len=7")
$Link(concat, lstm, "(516,)")
$FC(action_mlp, "FC", "256 → 2312")
$Link(lstm, action_mlp, "(256,)")
$FC(value_mlp, "FC", "256 → 1")
$Link(lstm, value_mlp, "(256,)")

$Output(action, "Action")
$Link(action_mlp, action, "(2312,)")

$Output(value, "Value")
$Link(value_mlp, value, "(1,)")

@enduml

